name: simple deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
      branches: [master]
      types: [ opened, synchronize ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000


  deployment_and_tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: deploy to internet
        uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
      - name: Success Build
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() || cancelled() }}
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: DEPLOYED
          details: to https://pokepedia.fly.dev by ${{ github.event.commits[0].committer.name }}
          text: A new version of pokedex deployed
      - name: Failed to build
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() || cancelled() }}
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: Commit broke the build
          details: ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.name }}
          text: BUILD FAILED
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1ffbb2e04bd950cffea99066469cb16d69a7887e
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
