name: simple deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
      branches: [master]
      types: [ opened, synchronize ]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm test
      - name: e2e test
        uses: cypress-io/github-action@v4
        with:
          build: npm run build
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: deploy to internet
        uses: superfly/flyctl-actions/setup-flyctl@master
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
      - run: flyctl deploy --remote-only
        if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
      - name: Success Build
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: DEPLOYED
          details: to https://pokepedia.fly.dev by ${{ github.event.commits[0].committer.name }}
          text: A new version of pokedex deployed
      - name: Failed to build
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          description: Commit broke the build
          details: ${{ github.event.commits[0].url }} by ${{ github.event.commits[0].committer.name }}
          text: BUILD FAILED
      - name: Check the deployed service URL
        uses: Jtalk/url-health-check-action@v3
        with:
          url: https://pokepedia.fly.dev/health
          max-attempts: 7
          retry-delay: 10s
          retry-all: true
          follow-redirect: true
  tag_release:
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ''), '#skip') }}
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

